apiVersion: v1
kind: Secret
metadata:
  name: prefect-token
data:
  prefectToken: "{{ .Values.prefectToken | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-token
data:
  jupyterHubToken: "{{ .Values.jupyterHubToken | b64enc }}"
