apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ index .Values "cert-manager" "ingressShim" "defaultIssuerName" }}
spec:
  acme:
    server: {{ .Values.clusterissuer.server }}
    email: {{ .Values.clusterissuer.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
