name: 'Kubernetes Testing'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  kubernetes:
    name: "Kubernetes Tests"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Download and Install Minikube and Kubectl
        run: |
          mkdir -p bin
          pushd bin
          curl -L https://github.com/kubernetes/minikube/releases/download/v1.15.0/minikube-linux-amd64 -o minikube
          chmod +x minikube

          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
          chmod +x kubectl

          echo "$PWD" >> $GITHUB_PATH
          popd
      - name: Start Minikube
        run: |
          minikube start --kubernetes-version=1.19.4 --driver=docker --wait=all
      - name: Enable Minikube Ingress
        run: |
          minikube addons enable ingress
      - name: Versions
        run: |
          minikube version
          kubectl version
      - name: Basic Kubectl Checks
        run: |
          kubectl get nodes
          kubectl get namespaces
          kubectl get pods -A
          kubectl get services -A
